#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Identity stays on this machine. Nothing here is written into the repo.
ENV_FILE="${HOME}/.config/dotfiles/gpg-signing.env"
mkdir -p "${HOME}/.config/dotfiles"

# Remember a value for the next run without marking it written yet.
remember_default() {
  local key="$1" value="$2"
  [[ -n "$value" ]] || return 0
  touch "$ENV_FILE"
  if grep -qE "^${key}=" "$ENV_FILE"; then
    return 0
  fi
  printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
}

find_brew() {
  if [[ -x /opt/homebrew/bin/brew ]]; then
    printf '/opt/homebrew/bin/brew\n'
    return 0
  fi
  if [[ -x /usr/local/bin/brew ]]; then
    printf '/usr/local/bin/brew\n'
    return 0
  fi
  if command -v brew >/dev/null 2>&1; then
    command -v brew
    return 0
  fi
  return 1
}

secret_key_ids() {
  local list type keyid
  list="$(gpg --list-secret-keys --with-colons --keyid-format=long 2>/dev/null || true)"
  while IFS=: read -r type _ _ _ keyid _; do
    if [[ "$type" == "sec" && -n "$keyid" ]]; then
      printf '%s\n' "$keyid"
    fi
  done <<< "$list"
}

require_tty() {
  local tty_path
  if ! tty_path="$(tty 2>/dev/null)"; then
    warn "Run this in a terminal so GnuPG can ask for a passphrase."
    exit 1
  fi
  export GPG_TTY="$tty_path"
}

has_secret_key() {
  local list type keyid
  list="$(gpg --list-secret-keys --with-colons --keyid-format=long "$1" 2>/dev/null || true)"
  while IFS=: read -r type _ _ _ keyid _; do
    if [[ "$type" == "sec" && "$keyid" == "$1" ]]; then
      return 0
    fi
  done <<< "$list"
  return 1
}

banner "GPG commit signing"

# ── Stage 1 ────────────────────────────────────────────────────────────────
stage "Verified email"
say "The email on the key must match your Git commit email."
say "GitHub verifies a signature only when that address is on your account."
open_url "https://github.com/settings/emails"
step "On Emails, choose a verified address."
step "To hide your address, copy the no-reply address on this page. It ends in @users.noreply.github.com."
step "Use that same address in Git and on the GPG key."

remember_default GIT_USER_NAME "$(git config --global --get user.name || true)"
remember_default GIT_USER_EMAIL "$(git config --global --get user.email || true)"

while true; do
  ask GIT_USER_NAME "Git name:"
  if [[ -n "${GIT_USER_NAME}" ]]; then
    break
  fi
  warn "A name is required."
done

while true; do
  ask GIT_USER_EMAIL "Git email:"
  if [[ "$GIT_USER_EMAIL" == *"@"* && "$GIT_USER_EMAIL" != *" "* ]]; then
    break
  fi
  warn "Enter one email address, with no spaces."
done

say "Name:  ${GIT_USER_NAME}"
say "Email: ${GIT_USER_EMAIL}"
if ! confirm "Save this name and email in your global Git config?"; then
  warn "Stopped. Git and the GPG key need the same email."
  exit 1
fi

git config --global user.name "$GIT_USER_NAME"
git config --global user.email "$GIT_USER_EMAIL"
write_env GIT_USER_NAME "$GIT_USER_NAME"
write_env GIT_USER_EMAIL "$GIT_USER_EMAIL"
note "Saved on this machine only. This repo still has ??? placeholders."

# ── Stage 2 ────────────────────────────────────────────────────────────────
stage "Install GnuPG"
brew_bin="$(find_brew || true)"
if [[ -n "$brew_bin" ]]; then
  eval "$("$brew_bin" shellenv)"
fi

if command -v gpg >/dev/null 2>&1 && command -v pinentry-mac >/dev/null 2>&1; then
  say "GnuPG and pinentry-mac are already installed."
else
  if [[ -z "$brew_bin" ]]; then
    warn "Homebrew is missing. Run ./bootstrap.sh, then run this script again."
    exit 1
  fi
  say "GnuPG signs commits. pinentry-mac asks for the passphrase."
  if ! confirm "Install gnupg and pinentry-mac with Homebrew?"; then
    warn "Stopped. Signing needs both tools."
    exit 1
  fi
  "$brew_bin" install gnupg pinentry-mac
  eval "$("$brew_bin" shellenv)"
  say "Installed."
fi

# ── Stage 3 ────────────────────────────────────────────────────────────────
stage "Generate a GPG key"
require_tty

existing_ids="$(secret_key_ids || true)"
if [[ -n "$existing_ids" ]]; then
  say "A secret key is already on this machine:"
  printf '\n'
  gpg --list-secret-keys --keyid-format=long || true
  printf '\n'
  if confirm "Generate another key anyway?"; then
    generate_key=1
  else
    generate_key=0
    say "Keeping the existing key."
  fi
else
  generate_key=1
fi

if [[ "$generate_key" -eq 1 ]]; then
  say "GnuPG will ask the questions below. This wizard does not see your passphrase."
  step "Kind of key: press Enter."
  step "Key size: press Enter."
  step "How long the key is valid: press Enter, so the key does not expire."
  step "When it asks if this is correct: type y."
  step "Real name: ${GIT_USER_NAME}"
  step "Email address: ${GIT_USER_EMAIL}"
  step "Comment: press Enter."
  step "When it asks (O)kay/(Q)uit: type O."
  step "Passphrase: type it in the GnuPG prompt. It is not saved here."
  if ! confirm "Generate the key now?"; then
    if [[ -z "$existing_ids" ]]; then
      warn "Stopped. There is no signing key yet."
      exit 1
    fi
    say "Keeping the existing key."
  else
    gpg --full-generate-key
  fi
fi

# ── Stage 4 ────────────────────────────────────────────────────────────────
stage "Choose the signing key"
printf '\n'
gpg --list-secret-keys --keyid-format=long || true
printf '\n'
say "The long key id is the 16 characters after the slash on the sec line."

existing_ids="$(secret_key_ids || true)"
key_count=0
only_key=""
while IFS= read -r keyid; do
  [[ -z "$keyid" ]] && continue
  key_count=$((key_count + 1))
  only_key="$keyid"
done <<< "$existing_ids"

if [[ "$key_count" -eq 0 ]]; then
  warn "No secret key found. Run this script again and generate one."
  exit 1
fi

if [[ "$key_count" -eq 1 ]]; then
  remember_default GPG_SIGNING_KEY "$only_key"
fi

while true; do
  ask GPG_SIGNING_KEY "Long key id to sign with:"
  GPG_SIGNING_KEY="${GPG_SIGNING_KEY##*/}"
  GPG_SIGNING_KEY="${GPG_SIGNING_KEY//[[:space:]]/}"
  GPG_SIGNING_KEY="$(printf '%s' "$GPG_SIGNING_KEY" | tr '[:lower:]' '[:upper:]')"
  if has_secret_key "$GPG_SIGNING_KEY"; then
    break
  fi
  warn "That id is not a secret key on this machine. Use the 16 character id."
done

current_signingkey="$(git config --global --get user.signingkey || true)"
if [[ -n "$current_signingkey" && "$current_signingkey" != "$GPG_SIGNING_KEY" ]]; then
  say "Git currently signs with ${current_signingkey}."
  if ! confirm "Replace it with ${GPG_SIGNING_KEY}?"; then
    warn "Stopped. The signing key was left unchanged."
    exit 1
  fi
fi

git config --global user.signingkey "$GPG_SIGNING_KEY"
git config --global commit.gpgsign true
git config --global tag.gpgSign true
if git config --global --get gpg.format >/dev/null 2>&1; then
  git config --global --unset gpg.format
  note "Cleared gpg.format so Git uses OpenPGP."
fi
write_env GPG_SIGNING_KEY "$GPG_SIGNING_KEY"
say "Git will sign commits and tags with ${GPG_SIGNING_KEY}."

# ── Stage 5 ────────────────────────────────────────────────────────────────
stage "Add the public key to GitHub"
if command -v pbcopy >/dev/null 2>&1; then
  gpg --armor --export "$GPG_SIGNING_KEY" | pbcopy
  say "The public key is on the clipboard."
else
  gpg --armor --export "$GPG_SIGNING_KEY"
  say "Copy the block above."
fi
note "It starts with -----BEGIN PGP PUBLIC KEY BLOCK-----"
note "and ends with -----END PGP PUBLIC KEY BLOCK-----."
open_url "https://github.com/settings/keys"
step "Next to the GPG keys header, click New GPG key."
step "In Title, type a name you will recognize for this computer."
step "Click the Key field and paste."
step "Click Add GPG key."
step "If GitHub asks you to confirm, complete that prompt."
if ! confirm "Did you click Add GPG key?"; then
  SKIPPED+=("Add the public key at https://github.com/settings/keys")
  warn "The key is not on GitHub yet. Signatures stay unverified until you add it."
fi

# ── Stage 6 ────────────────────────────────────────────────────────────────
stage "Passphrase prompt"
pinentry_bin="$(command -v pinentry-mac || true)"
if [[ -z "$pinentry_bin" ]]; then
  warn "pinentry-mac is not on PATH. Passphrase prompts may fail outside this terminal."
  SKIPPED+=("pinentry-program in ${HOME}/.gnupg/gpg-agent.conf")
else
  agent_conf="${HOME}/.gnupg/gpg-agent.conf"
  pinentry_line="pinentry-program ${pinentry_bin}"
  reload_agent=0
  if [[ -f "$agent_conf" ]] && grep -Fqx "$pinentry_line" "$agent_conf"; then
    say "pinentry-mac is already set in gpg-agent.conf."
    reload_agent=1
  elif confirm "Use pinentry-mac for passphrase prompts?"; then
    mkdir -p "${HOME}/.gnupg"
    chmod 700 "${HOME}/.gnupg"
    if [[ -f "$agent_conf" ]] && grep -qE '^pinentry-program ' "$agent_conf"; then
      tmp="$(mktemp)"
      grep -vE '^pinentry-program ' "$agent_conf" > "$tmp" || true
      printf '%s\n' "$pinentry_line" >> "$tmp"
      mv "$tmp" "$agent_conf"
    else
      touch "$agent_conf"
      printf '\n%s\n' "$pinentry_line" >> "$agent_conf"
    fi
    chmod 600 "$agent_conf"
    say "Wrote pinentry-program to ${agent_conf}."
    reload_agent=1
  else
    SKIPPED+=("pinentry-program in ${agent_conf}")
  fi
  if [[ "$reload_agent" -eq 1 ]]; then
    if command -v gpgconf >/dev/null 2>&1; then
      gpgconf --kill gpg-agent || true
    else
      killall gpg-agent >/dev/null 2>&1 || true
    fi
  fi
fi
note "New shells set GPG_TTY from cli/gpg.zsh. Open a new shell after this."

# ── Stage 7 ────────────────────────────────────────────────────────────────
stage "Test the signature"
say "GnuPG will ask for the passphrase. That checks the key and the prompt."
if confirm "Sign a one-line test message now?"; then
  require_tty
  if echo "gpg-sign-test" | gpg --local-user "$GPG_SIGNING_KEY" --clearsign; then
    say "The test signature succeeded."
  else
    warn "The test signature did not complete."
    SKIPPED+=("A successful gpg --clearsign test")
  fi
else
  SKIPPED+=("A successful gpg --clearsign test")
fi
say "The next Git commit is signed. On GitHub, open the commit and look for Verified."

finish
